-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE * 30 * (100-C.DISCOUNT_RATE) / 100 FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE 
    AND (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV')
    AND C.DURATION_TYPE = '30일 이상'
WHERE A.DAILY_FEE * 30 * (100-C.DISCOUNT_RATE) / 100 BETWEEN 500000 AND 2000001
AND A.CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= DATE'2022-11-30' AND END_DATE >= DATE'2022-11-01'
)
ORDER BY 3 DESC, 2, 1 DESC