-- 코드를 입력하세요


SELECT CAR_ID, CASE WHEN SUM(CNT) > 0 THEN '대여중' ELSE '대여 가능' END AVAILABILITY
FROM (
    SELECT CAR_ID,
    CASE WHEN CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= DATE '2022-10-16'
        AND END_DATE >= DATE '2022-10-16'
    ) THEN 1
    ELSE 0
    END CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
)
GROUP BY CAR_ID 
ORDER BY CAR_ID DESC