SELECT  A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE*B.TOTAL TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) TOTAL
    FROM FOOD_ORDER 
    WHERE PRODUCE_DATE >= DATE '2022-05-01' AND PRODUCE_DATE < DATE '2022-06-01'
    GROUP BY PRODUCT_ID
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID 


