-- 코드를 입력하세요
SELECT B.HISTORY_ID, A.DAILY_FEE*(B.END_DATE - B.START_DATE+1)*(100-NVL(C.DISCOUNT_RATE, 0))/100 FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID AND A.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.CAR_TYPE = C.CAR_TYPE
AND C.DURATION_TYPE = 
        CASE 
            WHEN B.END_DATE - B.START_DATE + 1 >= 90 THEN '90일 이상'
            WHEN B.END_DATE - B.START_DATE + 1 >= 30 THEN '30일 이상'
            WHEN B.END_DATE - B.START_DATE + 1 >= 7 THEN '7일 이상'
END
ORDER BY FEE DESC, HISTORY_ID DESC