-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
    FROM FIRST_HALF 
    GROUP BY FLAVOR

    UNION ALL 

    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL
    FROM JULY
    GROUP BY FLAVOR
)
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC
FETCH FIRST 3 ROW ONLY