# -- 코드를 입력하세요
# SELECT SUM(TOTAL_ORDER), FLAVOR
# FROM JULY
# GROUP BY FLAVOR

SELECT A.FLAVOR
FROM FIRST_HALF AS A
JOIN JULY AS B
ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) DESC
LIMIT 3