# -- 코드를 입력하세요
# SELECT C.APNT_NO, A.PT_NAME, C.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
# FROM APPOINTMENT C
# JOIN PATIENT A ON A.PT_NO = C.PT_NO
# JOIN DOCTOR  B ON B.DR_ID = C.MDDR_ID
# WHERE C.APNT_YMD >= '2022-04-13 00:00:00.000000'
# AND C.APNT_YMD < '2022-04-14 00:00:00.000000'
# AND C.APNT_CNCL_YN = 'N'
# AND C.MCDP_CD = 'CS'
# ORDER BY C.APNT_YMD

SELECT AP.APNT_NO, P.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP 
JOIN DOCTOR D ON D.DR_ID = AP.MDDR_ID
JOIN PATIENT P ON P.PT_NO = AP.PT_NO
WHERE AP.APNT_CNCL_YMD IS NULL AND AP.MCDP_CD = 'CS' AND AP.APNT_YMD LIKE '2022-04-13%'
ORDER BY AP.APNT_YMD