-- 코드를 작성해주세요
SELECT A.EMP_NO, A.EMP_NAME, 
CASE 
WHEN B.SCORE>=96 THEN 'S'
WHEN B.SCORE>=90 THEN 'A'
WHEN B.SCORE>=80 THEN 'B'
ELSE 'C' END
AS GRADE,
A.SAL*CASE 
WHEN B.SCORE>=96 THEN 0.2
WHEN B.SCORE>=90 THEN 0.15
WHEN B.SCORE>=80 THEN 0.1
ELSE 0 END
AS BONUS
FROM HR_EMPLOYEES AS A
JOIN (SELECT AVG(SCORE) AS SCORE, EMP_NO
FROM HR_GRADE 
GROUP BY EMP_NO) AS B
ON A.EMP_NO = B.EMP_NO
ORDER BY EMP_NO


