
SELECT B.HOUR, NVL(COUNT(A.DATETIME), 0) COUNT
FROM ANIMAL_OUTS A
RIGHT OUTER JOIN (
    SELECT LEVEL+8 HOUR
    FROM DUAL
    CONNECT BY LEVEL < 12
) B
ON TO_CHAR(DATETIME, 'HH24') = B.HOUR
GROUP BY B.HOUR
ORDER BY B.HOUR